In [6]:
import numpy as np
import theano.tensor as T
# from theano     theano.function
from theano import function

# 建立x容器
x=T.dscalar('x')
y=T.dscalar('y')
z=x+y
# 使用function定义theano的方程，将输入值x,y放在[]中，输出值放在后面
f=function([x,y],z)
print(f(2,3))

5.0


In [9]:
from theano import pp
# 使用（pretty-print）pp打印除原始方程
print(pp(z))

(x + y)


In [40]:
# 定义矩阵，以及相关运算
x=T.dmatrix('x')
y=T.dmatrix('y')
z=x+y
f=function([x,y],z)
# arange返回的是一个数组，
# reshape(行，列)注意-1情况
arr=np.arange(12)
#print(arr.reshape(-1,1))
print(arr.reshape(3,4))
# ones创建任意维度和元素个数数组，元素值都为1
print(np.ones((3,4)))
print(f(arr.reshape((3,4)),10*np.ones((3,4))))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 10.  11.  12.  13.]
 [ 14.  15.  16.  17.]
 [ 18.  19.  20.  21.]]


In [43]:
x=T.dmatrix('x')
s=1/(1+T.exp(-x))
logistic=function([x],s)
print(logistic([[0,1],[-2,-3]]))

[[ 0.5         0.73105858]
 [ 0.11920292  0.04742587]]


In [45]:
# 多输入多输出的function
# 假定输入值两个，输出也是两个，指定输入值矩阵a,b
a,b=T.dmatrices('a','b')
diff=a-b
abs_diff=abs(diff)
diff_squared=diff**2
f=function([a,b],[diff,abs_diff,diff_squared])
x1,x2,x3=f(
    np.ones((2,2)),
    np.arange(4).reshape((2,2))
)
print(x1,x2,x3)

[[ 1.  0.]
 [-1. -2.]] [[ 1.  0.]
 [ 1.  2.]] [[ 1.  0.]
 [ 1.  4.]]


In [70]:
# function的名字
x,y,w=T.dscalars('x','y','w')
z=(x+y)*w
f=theano.function([x,theano.In(y,value=1),theano.In(w,value=2)],z)
#使用默认值
print(f(23))
#不使用默认值
print(f(23,3,3))

48.0
78.0


In [71]:
#添加名字
f = theano.function([x,
                     theano.In(y, value=1),
                     theano.In(w,value=2,name='weights')],
                    z)
                    
print (f(23,1,weights=4)) ##调用方式

96.0


In [83]:
# 共享变量
import theano
state=theano.shared(np.array(0,dtype=np.float64),'state')# 初始化
# 不能使用np.float64指定类型，需要使用dtype=state.dtype
inc=T.scalar('inc',dtype=state.dtype)
accumulator=theano.function([inc],state,updates=[(state,state+inc)])
# get_value获取共享变量的值
print(state.get_value())
accumulator(1)
print(state.get_value())
# 设置共享变量的值
state.set_value(-1)
accumulator(10)
print(state.get_value())

0.0
1.0
9.0


In [ ]:
# 激励函数Activation function